apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-system
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root-user-credentials
  namespace: mongodb-system
type: Opaque
data:
  # echo -n root | base64
  username: cm9vdA==
  # echo -n X6d9r2SgJ8xQgpGL | base64
  password: WDZkOXIyU2dKOHhRZ3BHTA==
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-system
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongodb-system
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-root-user-credentials
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-root-user-credentials
              key: password
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
