apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: mongodb-system
spec:
  template:
    spec:
      containers:
      - name: dikino-jobs
        image: gryphon2411/dikino-jobs:latest
        args:
        - python
        - run.py
        - mongoinit.py
        env:
        - name: MONGO_URI_FORMAT
          value: mongodb
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-root-user-credentials
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-root-user-credentials
              key: password
        - name: MONGO_HOST
          value: mongodb.mongodb-system
      restartPolicy: Never
